In [1]:
import pandas as pd
import numpy as np
from plot_cdf import plot_cdf, plot_cdf_multiple
import matplotlib.pyplot as plt
import json
import os
import glob
import torch

In [2]:
pickle_path = "/home/dena/Documents/Gym_RTC/gym-example/rates_delay_loss.pickle"
l_rate = pd.read_pickle(pickle_path)

In [3]:
len(l_rate)

4

In [4]:
total_reward = []
avg_reward = []

for i in range(len(l_rate)):
    l_reward = l_rate[i]["reward"]
    total_reward.append(np.sum(l_reward))
    avg_reward.append(np.mean(l_reward))

cumulative_reward = np.cumsum(avg_reward)

In [5]:
cumulative_reward

array([0.24176457, 0.48401135, 0.71242824, 0.96555765])

In [6]:
total_reward

[69.86996, 70.00932, 66.01248000000001, 73.15440000000001]

In [11]:
avg_reward

[0.350815440245109,
 0.3536352027339055,
 0.35432115907932993,
 0.3521228207270077,
 0.3531488204240222,
 0.3576044158736055,
 0.35442859072175587,
 0.3470820396954254,
 0.3530207447555465]

In [16]:
state = np.random.rand(4,5)
state

array([[0.77822144, 0.90553545, 0.35645551, 0.96324961, 0.38930355],
       [0.38685035, 0.64710791, 0.11205128, 0.24669493, 0.49525394],
       [0.42244442, 0.2332793 , 0.1821964 , 0.10256148, 0.64619553],
       [0.0192837 , 0.37692295, 0.84492991, 0.53364953, 0.30959748]])

In [19]:
state[0, -1]

0.38930355448132503

In [26]:
np.roll(state, -1, axis=1)

array([[0.90553545, 0.35645551, 0.96324961, 0.38930355, 0.77822144],
       [0.64710791, 0.11205128, 0.24669493, 0.49525394, 0.38685035],
       [0.2332793 , 0.1821964 , 0.10256148, 0.64619553, 0.42244442],
       [0.37692295, 0.84492991, 0.53364953, 0.30959748, 0.0192837 ]])

In [1]:
import torch
state = torch.zeros((1, 4, 5))
state

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [11]:
state = torch.rand(size=(4, 5))
state

tensor([[0.7407, 0.9312, 0.6832, 0.2729, 0.3208],
        [0.7007, 0.8484, 0.9079, 0.7356, 0.2935],
        [0.8711, 0.9356, 0.7107, 0.1619, 0.7554],
        [0.4195, 0.2456, 0.3346, 0.2533, 0.8671]])

In [14]:
state[0, -1] = 5
state[1, -1] = 4

In [15]:
state

tensor([[0.7407, 0.9312, 0.6832, 0.2729, 5.0000],
        [0.7007, 0.8484, 0.9079, 0.7356, 4.0000],
        [0.8711, 0.9356, 0.7107, 0.1619, 0.7554],
        [0.4195, 0.2456, 0.3346, 0.2533, 0.8671]])

In [16]:
torch.roll(state, -1, dims=-1)

tensor([[0.9312, 0.6832, 0.2729, 5.0000, 0.7407],
        [0.8484, 0.9079, 0.7356, 4.0000, 0.7007],
        [0.9356, 0.7107, 0.1619, 0.7554, 0.8711],
        [0.2456, 0.3346, 0.2533, 0.8671, 0.4195]])